---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    redis_port: 6379
    redis_databases: 1
    redis_maxmemory: 312mb
    redis_eviction_policy: volatile-ttl

  tasks:
    - name: Update
      apt: update_cache=yes

    - name: install redis
      apt:
        name: redis
        state: present
    
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-setuptools

    - name: Install additional python modules
      pip:
        executable: pip3
        name: 
          - redis
          - pyserial
    
    - name: Ensure Redis Configuration
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
      notify: Redis Restart

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: redis-server
        enabled: yes

  handlers:
   - name: Redis Restart
     service: name=redis-server state=restarted enabled=yes
