---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    redis_port: 6379
    redis_databases: 1
    redis_maxmemory: 312mb
    redis_eviction_policy: volatile-ttl

  tasks:
    - name: Update
      apt: update_cache=yes

    - name: install redis
      apt:
        name: redis
        state: present
    
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-setuptools

    - name: Install additional python modules
      pip:
        executable: pip3
        name: 
          - redis
          - pyserial
          - google-cloud-pubsub
    
    - name: Ensure Redis Configuration
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
      notify: Redis Restart

    - name: Enable service redis, and not touch the state
      ansible.builtin.service:
        name: redis-server
        state: started
        enabled: yes

    - name: UART Reader - systemd file
      template: src=iot_uart_reader.service.j2 dest=/lib/systemd/system/iot_uart_reader.service mode=644

    - name: Msg pubsub pubslisher - systemd file
      template: src=iot_msg_publisher_pubsub.service.j2 dest=/lib/systemd/system/iot_msg_publisher.service mode=644

    - name: Msg graphite pubslisher - systemd file
      template: src=iot_msg_publisher_graphite.service.j2 dest=/lib/systemd/system/iot_msg_publisher_graphite.service mode=644

    - name: Msg pubsub publisher - systemd service
      service: name=iot_msg_publisher.service state=started enabled=yes

    - name: Msg graphite publisher - systemd service
      service: name=iot_msg_publisher_graphite.service state=started enabled=yes

    - name: UART Reader - systemd service
      service: name=iot_uart_reader.service state=started enabled=yes


  handlers:
   - name: Redis Restart
     service: name=redis-server state=restarted enabled=yes